## Data cleaning and preparation
- Handling Missing Data
- Correcting Data Types
- Removing Duplicates
- Outlier Detection and Treatment
- Standardization and Normalization
- Encoding Categorical Variables
- Feature Engineering

In [204]:
import pandas as pd
import numpy as np

In [205]:

df = pd.read_excel(r"data/Customer Call List.xlsx")  
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [206]:
df = df.drop_duplicates()

In [207]:
# inplace = True updates the original dataframe
df.drop(columns=["Not_Useful_Column"] , inplace=True) 
df

C:\Users\User\AppData\Local\Temp\ipykernel_23520\4264070319.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Not_Useful_Column"] , inplace=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [208]:
df['Last_Name'] = df['Last_Name'].str.strip()
df['First_Name'] = df['First_Name'].str.strip()
df['Last_Name'] = df['Last_Name'].str.strip('123._/')
df

C:\Users\User\AppData\Local\Temp\ipykernel_23520\2757176966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df['Last_Name'].str.strip()
C:\Users\User\AppData\Local\Temp\ipykernel_23520\2757176966.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['First_Name'] = df['First_Name'].str.strip()
C:\Users\User\AppData\Local\Temp\ipykernel_23520\2757176966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df['Last_Name'].str.strip('123._/')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
# some of the numbers are strings and some are integers. When you run the string method during the formatting,
#  it replaces the numeric values with NaN and they are later removed completely.
df["Phone_Number"] = df["Phone_Number"].astype(str)
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','',regex=True)
# Use .map() when working with a Series and you need simple transformations or mappings.
# Use .apply() for complex operations or when working with a DataFrame.
df ['Phone_Number'] = df['Phone_Number'].map(lambda x: str(x)[0:3] + '-' + str(x)[3:6] + '-' + str(x)[6:10])
# df['Phone_Number'].dropna(axis=0)
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
# Performance: The .str.replace() method tends to be faster than apply() for large datasets, 
# so it's generally the preferred method for string manipulations in pandas.
# def fill_scores(score):  
#     if score == 'nan--':  
        
#         return ''
#     if score == 'Na--':  
        
#         return ''
#     return score  

# df['Phone_Number'].apply(fill_scores)  
df

C:\Users\User\AppData\Local\Temp\ipykernel_23520\4266252939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].astype(str)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\4266252939.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','',regex=True)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\4266252939.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ['Phone_Number'] = df['Phone_Number'].map(lambda x: str(x)[0:3] + '-' + str(x)[3:6] + '-' + str(x)[6:10])
C:\Users\User\AppData\Local\Temp\ipykernel_23520\4266252939.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
C:\Users\User\AppData\Local\Temp\ipykernel_23520\4266252939.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [210]:
df[['Address', 'State', 'Postal Code']] = df['Address'].str.split(',', n=2, expand=True)
df

C:\Users\User\AppData\Local\Temp\ipykernel_23520\1235300189.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Address', 'State', 'Postal Code']] = df['Address'].str.split(',', n=2, expand=True)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\1235300189.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Address', 'State', 'Postal Code']] = df['Address'].str.split(',', n=2, expand=True)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\1235300189.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Address', 'State', 'Postal Code']] = df['Address'].str.split(',', n=2, expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Yes,No,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Yes,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Yes,No,New York,None
10,1011,Samwise,Gamgee,,612 Shire Lane,Yes,No,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Yes,No,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Yes,N,Tatooine,None

In [211]:
df.loc[: ,'Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df.loc[: ,'Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')

# loc : This way, you ensure that you are modifying the DataFrame directly without creating a potentially ambiguous copy.
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,No,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,None,None
6,1007,Jeff,Winger,,1209 South Street,N,No,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,No,New York,None
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,No,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,No,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None

In [212]:
df.loc[: ,'Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df.loc[: ,'Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,None
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,N,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None

In [213]:
df['Phone_Number'] = df['Phone_Number'].replace('--', np.nan )
df = df.replace('N/a' , '')
df = df.replace('NaN' , '')
df = df.fillna('')

df

C:\Users\User\AppData\Local\Temp\ipykernel_23520\3618368104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].replace('--', np.nan )

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,,
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,,
6,1007,Jeff,Winger,,1209 South Street,N,N,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,
8,1009,Gandalf,,,123 Middle Earth,Y,,,
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,N,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,,
18,1019,Creed,Braton,,,,Y,,
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,

In [214]:
#df.loc[row_indexer, column_indexer] = value  

# .loc: Label-based indexing (uses row and column labels).
# .iloc: Integer-based indexing (uses row and column positions).

# Select rows 'a' to 'b' (inclusive) for all columns
# range_rows = df.loc["a":"b"]

# Select rows where Age > 25
# age_filter = df.loc[df["Age"] > 25]

# Add a new column
# df.loc[:, "Country"] = ["USA", "USA", "USA"]


for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

# another way
# df['Phone_Number' ].replace('', np.nan , inplace=True)
# df = df.dropna(subset=["Phone_Number"])  

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,,
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,

In [215]:
df.reset_index(drop=True, inplace=True) 
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Postal Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,,
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,,
6,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,
7,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,
8,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,,
9,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,
10,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,
11,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,
12,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,
13,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,
14,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,,
15,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,